# Generated by Django 6.0.1 on 2026-01-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalreport",
            name="extracted_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
